apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deploy
  labels:
    app: webapi
  namespace: perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: autodeployment
          image: aksperflabacr.azurecr.io/aksperflab-webapi:latest
          ports:
            - containerPort: 5000
