apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  labels:
    app: webapp
  namespace: perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: aksperflabacr.azurecr.io/aksperflab-webapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: SQLSERVERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: SQLSERVERNAME
            - name: SQLSERVERDBNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: SQLSERVERDBNAME
            - name: SQLUSERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: SQLUSERNAME
            - name: SQLPASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: SQLPASSWORD
            - name: WEBAPIURL
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: WEBAPIURL
