apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  labels:
    app: webapp
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: autodeployment
          image: aksperflabacr.azurecr.io/aksperflab-webapp:latest
          ports:
            - containerPort: 5000
